### ISSUE TITLE
Update challenge-base and simple-nft branches, show NFT on sepolia starkscan 

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/speedrunstark#93]
## Issue Overview

- Update `challenge-base` branch to use the latest components and dependencies of [scaffold-stark release](https://github.com/Quantum3-Labs/scaffold-stark-2/releases/tag/v0.2.2) 
- challenge base is a base setup for all the challenges in other branches.
- Update `simple-nft` challenge ( branch ) with the challenge-base and migrate Smart contract NFT to be follow OZ standard and when deploying on sepolia to be able to show NFT images on starkscan.

## Proposed Solutions or Ideas

- starkscan will check for the contract to follow `supports_interface` entry point in order for pictures to show up on the explorer.
- functions that starkscan checks for ( in order to show NFT image on explorer)

```bash 
      balance_of
      owner_of
      safe_transfer_from
      transfer_from
      approve
      balance_of
      set_approval_for_all
      get_approved
      is_approved_for_all
      supports_interface
```

**Comment by danielcdz** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello! My name is Daniel Calderon, I'm a software engineer from Costa Rica with over 3 years of experience, also, I'm an OSS contributor in OnlyDust, you can check my profile! I would love to solve this issue because Speedrun is a tool I used to learn how to mint NFTs a couple of months ago

### How I plan on tackling this issue
I will solve this issue by updating the dependencies in the required branch.

I will update the smart-contract to follow the Open Zepelin standard to show the images on block explorers.

I will perform some testing to ensure that the NFTs are shown in the block explorer and the deployment of the contract is working as expected.

**Comment by wugalde19** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hi Speedrun & Scaffold Stark team,
I’m William from Costa Rica 🇨🇷 and member of the Dojo Coding community.
I am interested in contributing to this issue and believe my skills and background make me well-suited for the task. I’ve worked over 7 years as Full Stack engineer in several technologies (including the ones used on this project JS, Typescript) and I am currently expanding my expertise in Rust, Cairo, and Solidity.

I’ve participated in two past OD Hack events and the StarkHack event organized by ETHGlobal.
On the Starkhack we used this project to create ours.
In our project we had to interact with NFTs and used your documentation and examples to do so
That’s why I consider that I will be able to contribute with this issue

Profiles:
https://app.onlydust.com/u/wugalde19
https://github.com/wugalde19


### How I plan on tackling this issue
Based on my understanding of the issue description, the core problem appears to be that you want to us to update some challenge branches to make use of new components and dependencies from your latest release. Also I’ll need to check the contract and check the supports_interface to make it possible for pictures to show up on the explorer, which seems to be easy once I understand the interface and check a few examples on how I did it in the past.
I can also reference to other projects and see how they did it in case I’m omitting something 
I’d also keep communicating my progress with you to ask for feedback since the beginning.

I’d then
- Update dependencies
- Check in Open Zepellin the ERC721 contract to understand better what “methods” do I have to use and implement in order to make them appear/to show in the explorer
- I’d also check in other projects to get ideas on how they did it
- I’m gonna be adding tests if required and test my changes locally (devnet) and then sepolia


Thank you, and I look forward to your guidance and to start contributing to this project.
